config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :vendors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'dashboard' => 'dashboard#index'

  root 'dashboard#index'

  resources :vehicle_owners

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle_owner.rb
class VehicleOwner < ApplicationRecord
  has_one_attached :image

  validates :mobile_number, uniqueness: true, presence: true, length: { is: 10 }
  
  def name
    "#{first_name} #{last_name}"
  end
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_vendor!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/vehicle_owners_controller.rb
class VehicleOwnersController < ApplicationController
  before_action :set_vo, only: [:show, :edit, :update, :destroy]

  def index
    @vehicle_owners = VehicleOwner.all
  end

  def show
  end

  def new
    @vehicle_owner = VehicleOwner.new
  end

  def create
    vehicle_owner = VehicleOwner.new(vo_params)
    if vehicle_owner.save
      flash[:success] = "Vehicle Owner added successfully."
      redirect_to vehicle_owners_path
    else
      flash[:error] = vehicle_owner.errors.full_messages[0]
      redirect_to new_vehicle_owner_path
    end
  end

  def edit
    
  end

  def update
    if @vehicle_owner.update(vo_params)
      flash[:success] = "Vehicle Owner updated successfully."
      redirect_to vehicle_owner_path(@vehicle_owner)
    else
      flash[:error] = vehicle_owner.errors.full_messages[0]
      redirect_to edit_vehicle_owner_path(@vehicle_owner)
    end
  end

  def destroy
    
  end

  private

  def vo_params
    params.require(:vehicle_owner).permit(:email, :first_name, :last_name, :mobile_number, :alt_mobile_number, :address, :status, :image)
  end

  def set_vo
    @vehicle_owner = VehicleOwner.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<main>
  <div class="container-fluid">
    <h2 class="mt-30 page-title">Dashboard</h2>
    <ol class="breadcrumb mb-30">
      <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <div class="row">
      <div class="col-xl-3 col-md-6">
        <div class="dashboard-report-card purple">
          <div class="card-content">
            <span class="card-title">Order Pending</span>
            <span class="card-count">2</span>
          </div>
          <div class="card-media">
            <i class="fab fa-rev"></i>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-md-6">
        <div class="dashboard-report-card red">
          <div class="card-content">
            <span class="card-title">Order Cancel</span>
            <span class="card-count">0</span>
          </div>
          <div class="card-media">
            <i class="far fa-times-circle"></i>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-md-6">
        <div class="dashboard-report-card info">
          <div class="card-content">
            <span class="card-title">Order Process</span>
            <span class="card-count">5</span>
          </div>
          <div class="card-media">
            <i class="fas fa-sync-alt rpt_icon"></i>
          </div>
        </div>
      </div>
      <div class="col-xl-3 col-md-6">
        <div class="dashboard-report-card success">
          <div class="card-content">
            <span class="card-title">Today Income</span>
            <span class="card-count">$9568.00</span>
          </div>
          <div class="card-media">
            <i class="fas fa-money-bill rpt_icon"></i>
          </div>
        </div>
      </div>
      <div class="col-xl-12 col-md-12">
        <div class="card card-static-1 mb-30">
          <div class="card-body">
            <div id="earningGraph"></div>
          </div>
        </div>
      </div>
      <div class="col-xl-12 col-md-12">
        <div class="card card-static-2 mb-30">
          <div class="card-title-2">
            <h4>Recent Orders</h4>
            <a href="orders.html" class="view-btn hover-btn">View All</a>
          </div>
          <div class="card-body-table">
            <div class="table-responsive">
              <table class="table ucp-table table-hover">
                <thead>
                  <tr>
                    <th style="width:130px">Order ID</th>
                    <th>Item</th>
                    <th style="width:200px">Date</th>
                    <th style="width:300px">Address</th>
                    <th style="width:130px">Status</th>
                    <th style="width:130px">Total</th>
                    <th style="width:100px">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>ORDER12345</td>
                    <td>
                      <a href="#" target="_blank">Product Title Here</a>
                    </td>
                    <td>
                      <span class="delivery-time">15/06/2020</span>
                      <span class="delivery-time">4:00PM - 6.00PM</span>
                    </td>
                    <td>#0000, St No. 8, Shahid Karnail Singh Nagar, MBD Mall, Frozpur road, Ludhiana, 141001</td>
                    <td>
                      <span class="badge-item badge-status">Pending</span>
                    </td>
                    <td>$90</td>
                    <td class="action-btns">
                      <a href="order_view.html" class="views-btn"><i class="fas fa-eye"></i></a>
                      <a href="order_edit.html" class="edit-btn"><i class="fas fa-edit"></i></a>
                    </td>
                  </tr>
                  <tr>
                    <td>ORDER12346</td>
                    <td>
                      <a href="#" target="_blank">Product Title Here</a>
                    </td>
                    <td>
                      <span class="delivery-time">13/06/2020</span>
                      <span class="delivery-time">2:00PM - 4.00PM</span>
                    </td>
                    <td>#0000, St No. 8, Shahid Karnail Singh Nagar, MBD Mall, Frozpur road, Ludhiana, 141001</td>
                    <td>
                      <span class="badge-item badge-status">Pending</span>
                    </td>
                    <td>$105</td>
                    <td class="action-btns">
                      <a href="order_view.html" class="views-btn"><i class="fas fa-eye"></i></a>
                      <a href="order_edit.html" class="edit-btn"><i class="fas fa-edit"></i></a>
                    </td>
                  </tr>
                  <tr>
                    <td>ORDER12347</td>
                    <td>
                      <a href="#" target="_blank">Product Title Here</a>
                    </td>
                    <td>
                      <span class="delivery-time">13/6/2020</span>
                      <span class="delivery-time">5:00PM - 7.00PM</span>
                    </td>
                    <td>#0000, St No. 8, Shahid Karnail Singh Nagar, MBD Mall, Frozpur road, Ludhiana, 141001</td>
                    <td>
                      <span class="badge-item badge-status">Pending</span>
                    </td>
                    <td>$60</td>
                    <td class="action-btns">
                      <a href="order_view.html" class="views-btn"><i class="fas fa-eye"></i></a>
                      <a href="order_edit.html" class="edit-btn"><i class="fas fa-edit"></i></a>
                    </td>
                  </tr>
                  <tr>
                    <td>ORDER12348</td>
                    <td>
                      <a href="#" target="_blank">Product Title Here</a>
                    </td>
                    <td>
                      <span class="delivery-time">12/06/2020</span>
                      <span class="delivery-time">01:00PM - 3.00PM</span>
                    </td>
                    <td>#0000, St No. 8, Shahid Karnail Singh Nagar, MBD Mall, Frozpur road, Ludhiana, 141001</td>
                    <td>
                      <span class="badge-item badge-status">Pending</span>
                    </td>
                    <td>$120</td>
                    <td class="action-btns">
                      <a href="order_view.html" class="views-btn"><i class="fas fa-eye"></i></a>
                      <a href="order_edit.html" class="edit-btn"><i class="fas fa-edit"></i></a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SRL</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <% if vendor_signed_in? %>
    <body class="sb-nav-fixed">
      <%= render 'layouts/shared/header' %>
      <div id="layoutSidenav">
        <%= render 'layouts/shared/sidenav' %>
        <div id="layoutSidenav_content">
          <%= render 'layouts/shared/messages' %>
          <%= yield %>
          <%= render 'layouts/shared/footer' %>
        </div>
      </div>
    </body>
  <% else %>
    <%= yield %>
  <% end %>
  <%= javascript_include_tag 'highcharts', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'exporting', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'export-data', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'accessibility', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'scripts', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'chart', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/shared/_footer.html.haml
%footer.py-4.bg-footer.mt-auto
  .container-fluid
    .d-flex.align-items-center.justify-content-between.small
      .text-muted-1
        © #{Time.now.year}
        = succeed "" do
          %b Surya Road Lines
          By Illusion IT Labs
      .footer-links
        %a{href: "/"} Privacy Policy
        %a{href: "/"} Terms &amp; Conditions

app/views/layouts/shared/_header.html.haml
%nav.sb-topnav.navbar.navbar-expand.navbar-light.bg-clr
  %a.navbar-brand.logo-brand{href: "/dashboard"} Surya Roadlines
  %button#sidebarToggle.btn.btn-link.btn-sm.order-1.order-lg-0{href: "#"}
    %i.fas.fa-bars
  %a.frnt-link{href: "/dashboard"}
    %i.fas.fa-external-link-alt>
    Home
  %ul.navbar-nav.ml-auto.mr-md-0
    %li.nav-item.dropdown
      %a#userDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
        %i.fas.fa-user.fa-fw
      .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "userDropdown"}
        = link_to "Change Password", class: "dropdown-item admin-dropdown-item"
        = link_to "Logout", class: "dropdown-item admin-dropdown-item"

app/views/layouts/shared/_messages.html.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", href: "#"} ×
    %ul
      %li
        = value

app/views/layouts/shared/_sidenav.html.erb
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <a class="nav-link active" href="index.html">
          <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
          Dashboard
        </a>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
          <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
          Vehicle Owners
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%= link_to "All Owners", vehicle_owners_path, class: "nav-link sub_nav_link" %>
            <%= link_to "Add New", new_vehicle_owner_path, class: "nav-link sub_nav_link" %>
          </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLocations" aria-expanded="false" aria-controls="collapseLocations">
          <div class="sb-nav-link-icon"><i class="fas fa-map-marker-alt"></i></div>
          Locations
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseLocations" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link sub_nav_link" href="locations.html">All Locations</a>
            <a class="nav-link sub_nav_link" href="add_location.html">Add Location</a>
          </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAreas" aria-expanded="false" aria-controls="collapseAreas">
          <div class="sb-nav-link-icon"><i class="fas fa-map-marked-alt"></i></div>
          Areas
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseAreas" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link sub_nav_link" href="areas.html">All Areas</a>
            <a class="nav-link sub_nav_link" href="add_area.html">Add Area</a>
          </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCategories" aria-expanded="false" aria-controls="collapseCategories">
          <div class="sb-nav-link-icon"><i class="fas fa-list"></i></div>
          Categories
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseCategories" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link sub_nav_link" href="category.html">All Categories</a>
            <a class="nav-link sub_nav_link" href="add_category.html">Add Category</a>
          </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseShops" aria-expanded="false" aria-controls="collapseShops">
          <div class="sb-nav-link-icon"><i class="fas fa-store"></i></div>
          Shops
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseShops" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <%#= link_to "My shops", vendor_shops_path, class: "nav-link sub_nav_link" %>
            <% if false %>
              <%= link_to "Edit Shop", edit_vendor_shop_path(@shop), class: "nav-link sub_nav_link" %>
            <% else %>
              <%#= link_to "Add Shop", new_vendor_shop_path, class: "nav-link sub_nav_link" %>
            <% end %>
          </nav>
        </div>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProducts" aria-expanded="false" aria-controls="collapseProducts">
          <div class="sb-nav-link-icon"><i class="fas fa-box"></i></div>
          Products
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseProducts" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link sub_nav_link" href="products.html">All Products</a>
            <a class="nav-link sub_nav_link" href="add_product.html">Add Product</a>
          </nav>
        </div>
        <a class="nav-link" href="orders.html">
          <div class="sb-nav-link-icon"><i class="fas fa-cart-arrow-down"></i></div>
          Orders
        </a>
        <a class="nav-link" href="customers.html">
          <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
          Customers
        </a>
        <a class="nav-link" href="offers.html">
          <div class="sb-nav-link-icon"><i class="fas fa-gift"></i></div>
          Offers
        </a>
        <a class="nav-link" href="pages.html">
          <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
          Pages
        </a>
        <a class="nav-link" href="menu.html">
          <div class="sb-nav-link-icon"><i class="fas fa-layer-group"></i></div>
          Menu
        </a>
        <a class="nav-link" href="updater.html">
          <div class="sb-nav-link-icon"><i class="fas fa-cloud-upload-alt"></i></div>
          Updater
        </a>
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseSettings" aria-expanded="false" aria-controls="collapseSettings">
          <div class="sb-nav-link-icon"><i class="fas fa-cog"></i></div>
          Setting
          <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>
        <div class="collapse" id="collapseSettings" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link sub_nav_link" href="general_setting.html">General Settings</a>
            <a class="nav-link sub_nav_link" href="payment_setting.html">Payment Settings</a>
            <a class="nav-link sub_nav_link" href="email_setting.html">Email Settings</a>
          </nav>
        </div>
        <a class="nav-link" href="reports.html">
          <div class="sb-nav-link-icon"><i class="fas fa-chart-bar"></i></div>
          Reports
        </a>
      </div>
    </div>
  </nav>
</div>

app/views/vehicle_owners/_form.html.haml
%main
  .container-fluid
    %h2.mt-30.page-title Vehicle Owner
    %ol.breadcrumb.mb-30
      %li.breadcrumb-item
        %a{href: "index.html"} Dashboard
      %li.breadcrumb-item
        %a{href: "shops.html"} Vehicle Owner
      %li.breadcrumb-item.active
        = params[:action]
        vehicle owner
    = form_for @vehicle_owner do |f|
      .row
        .col-lg-12
          .add-new-shop
            .card.card-static-2.mb-30
              .row.no-gutters
                .col-lg-12.col-md-12
                  .card-title-2
                    %h4 Add Vehicle Owner
                  .card-body-table
                    .add-shop-content.pd-20
                      .form-group
                        %label.form-label First Name*
                        = f.text_field :first_name, class:"form-control", placeholder: "First Name", required: true
                      .form-group
                        %label.form-label Last Name*
                        = f.text_field :last_name, class:"form-control", placeholder: "Last Name", required: true
                      .form-group
                        %label.form-label Email
                        = f.email_field :email, class:"form-control"
                      .form-group
                        %label.form-label Mobile Number*
                        = f.number_field :mobile_number, class:"form-control", required: true
                      .form-group
                        %label.form-label Alternat Mobile Number
                        = f.number_field :alt_mobile_number, class:"form-control"
                      .form-group
                        %label.form-label Address*
                        = f.text_area :address, class:"text-control", required: true
                      .form-group
                        %label.form-label Image
                        = f.file_field :image, class: "form-control"
          %div
            = f.submit "submit", class:"save-btn hover-btn"

app/views/vehicle_owners/edit.html.haml
= render 'form'

app/views/vehicle_owners/index.html.haml
%main
  .container-fluid
    %h2.mt-30.page-title Vehicle Owners
    %ol.breadcrumb.mb-30
      %li.breadcrumb-item
        %a{href: "index.html"} Dashboard
      %li.breadcrumb-item.active Vehicle Owners
    .row.justify-content-between
      .col-lg-12
        %a.add-btn.hover-btn{href: "/vehicle_owners/new"} Add New
      .col-lg-3.col-md-4
        .bulk-section.mt-30
          .input-group
            %select#action.form-control{name: "action"}
              %option{selected: "selected"} Bulk Actions
              %option{value: "1"} Active
              %option{value: "2"} Inactive
              %option{value: "3"} Delete
            .input-group-append
              %button.status-btn.hover-btn{type: "submit"} Apply
      .col-lg-5.col-md-6
        .bulk-section.mt-30
          .search-by-name-input
            %input.form-control{placeholder: "Search"}/
          .input-group
            %select#categeory.form-control{name: "categeory"}
              %option{selected: "selected"} Active
              %option{value: "1"} Inactive
            .input-group-append
              %button.status-btn.hover-btn{type: "submit"} Search owners
      .col-lg-12.col-md-12
        .card.card-static-2.mt-30.mb-30
          .card-title-2
            %h4 All Owners
          .card-body-table
            .table-responsive
              %table.table.ucp-table.table-hover
                %thead
                  %tr
                    %th{style: "width:60px"}
                      %input.check-all{type: "checkbox"}/
                    %th{style: "width:60px"} ID
                    %th Image
                    %th Name
                    %th Mobile Number
                    %th Alternat Mobile Number
                    %th Address
                    %th Total Vehicle(s)
                    %th{style: "width: 120px;"} Status
                    %th{style: "width: 150px;"} Action
                %tbody
                  - @vehicle_owners.each_with_index do |vehicle_owner, index|
                    %tr
                      %td
                        %input.check-item{name: "ids[]", type: "checkbox", value: "5"}/
                      %td= index+1
                      %td= image_tag(url_for(vehicle_owner.image), width: "50px", height: "50px") rescue nil
                      %td= vehicle_owner.name
                      %td= vehicle_owner.mobile_number
                      %td= vehicle_owner.alt_mobile_number
                      %td= vehicle_owner.address
                      %td= 0
                      %td
                        %span.badge-item.badge-status= vehicle_owner.status ? "Active" : "Inactive"
                      %td.action-btns
                        = link_to vehicle_owner_path(vehicle_owner), class: "view-shop-btn" do
                          %i.fas.fa-eye
                        %a.list-btn{href: "shop_products.html"}
                          %i.fas.fa-list-alt
                        = link_to edit_vehicle_owner_path(vehicle_owner), class: "edit-btn" do
                          %i.fas.fa-edit

app/views/vehicle_owners/new.html.haml
= render 'form'

app/views/vehicle_owners/show.html.haml
%main
  .container-fluid
    %h2.mt-30.page-title Vehicle Owner
    %ol.breadcrumb.mb-30
      %li.breadcrumb-item
        %a{href: "index.html"} Dashboard
      %li.breadcrumb-item
        %a{href: "shops.html"} Vehicle Owner
      %li.breadcrumb-item.active owner view
    .row
      .col-lg-4.col-md-5
        .card.card-static-2.mb-30
          .card-body-table
            .shop-content-left.pd-20
              .shop_img
                = image_tag(url_for(@vehicle_owner.image))
              .shop-dt-left
                %h4= @vehicle_owner&.name
                %span= @vehicle_owner&.address
        .card.card-static-2.mb-30
          .card-body-table
            .shopowner-content-left.pd-20
              .shopowner-dt-left
                %h4= @vehicle_owner&.name
                %span Vehicle Owner
              .shopowner-dts
                .shopowner-dt-list
                  %span.left-dt Phone
                  %span.right-dt= @vehicle_owner&.mobile_number
                .shopowner-dt-list
                  %span.left-dt Email
                  %span.right-dt= @vehicle_owner&.email
                .shopowner-dt-list
                  %span.left-dt Address
                  %span.right-dt= @vehicle_owner&.address
                .shopowner-dt-list
                  %span.left-dt Active
                  %span.right-dt= @vehicle_owner.status ? "Yes" : "No" 
      .col-lg-8.col-md-7
        .card.card-static-2.mb-30
          .card-body-table
            .shopowner-content-left.pd-20
              .shopowner-dts.mt-0
                .shopowner-dt-list
                  %span.left-dt Total Vehicle 
                  %span.right-dt 06
                .shopowner-dt-list
                  %span.left-dt Total Trips
                  %span.right-dt 125
                .shopowner-dt-list
                  %span.left-dt This months trip
                  %span.right-dt
                .shopowner-dt-list
                  %span.left-dt Total Income
                  %span.right-dt 1200000
                .shopowner-dt-list
                  %span.left-dt This Month Income
                  %span.right-dt 50000
                .shopowner-dt-list
                  %span.left-dt Longitude
                  %span.right-dt
                .shopowner-dt-list
                  %span.left-dt Current Status
                  %span.right-dt Yes
                .shopowner-dt-list
                  %span.left-dt Status
                  %span.right-dt Active
                .shopowner-dt-list
                  %span.left-dt Opening Time
                  %span.right-dt
                .shopowner-dt-list
                  %span.left-dt Close Time
                  %span.right-dt
                .shopowner-dt-list
                  %span.left-dt Address
                  %span.right-dt
                .shopowner-dt-list
                  %span.left-dt Description
                  %span.right-dt

app/views/vendors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/vendors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>